### ISSUE TITLE
Integration in third-party application

### ISSUE THREAD

**Issue by bartbutenaers** [bobboteck/JoyStick#15]
Hi Roberto (@bobboteck),

Thanks for sharing this library!
I would like to integrate your widget into an open-source application (as child of a DIV element...), but I have some questions about this:
+ Is it possible to show only the canvas and not the other widgets?
+ Is there also an NPM package available?

Happy christmas!
Bart

**Comment by bobboteck** [comment]
Hi @bartbutenaers, thank you for taking into consideration my library, I try to answer your questions.

1. I did not understand what other widgets you are referring to, to use the JoyStick it is sufficient to refer to a DIV when you initialize the JoyStick object in JavaScript (https://github.com/bobboteck/JoyStick#how-to-use-it ). If you were talking about the Text Boxes, visible in the example page, those I had inserted only for demonstration purposes, they are not part of the component.
2. I'm sorry, but at the moment I haven't made an NPM package, never having had the need, but it could be an idea to implement for the future, since up to now I have only made one with poor results 😄 

Let me know if my answers were comprehensive, or if I can be of any help to you.

P.S. I activated the Discussions feature in GitHub, you can also use that channel to ask as many questions as you want.

**Comment by bartbutenaers** [comment]
Morning @bobboteck,
I was indeed referring to the text boxes.  I had understood that those where always added.  So that is ok then for me.

The NPM package would be very nice to have.  Then I can simply add a dependency to your NPM package, which would be installed automatically.   And when you publish a new (minor) version, that would also be installed automatically, without me having to release a new version of my package.  So hopefully you still consider to create one.  If so, I will be glad to assist you with this!!!

I have some other feature requests, but will use the Github discussions to do that.
Thanks again!!

**Comment by bobboteck** [comment]
The package is available on NPM: https://www.npmjs.com/package/html5-joystick
