### ISSUE TITLE
Joystick Stays At Position When Cursor Let Go Outside of Joystick 

### ISSUE THREAD

**Issue by kethan1** [bobboteck/JoyStick#19]
When I let go of my cursor outside of the joystick, the joystick stays. GIF:

![2021-03-17-12-48-38](https://user-images.githubusercontent.com/33791257/111719040-48fc0280-8818-11eb-8ed6-7ade193989db.gif)

**Comment by bobboteck** [comment]
I can't see the picture, but I think I understand what you mean. If you have also noticed with touch devices it behaves the same way, with the only difference that lifting them with your finger brings them back into position. On a device in which you use the mouse or similar, instead as you have noticed it is as if the button were pressed, you have to click again to "free" it.
It is a special use case, I never looked for a solution, because I always thought it did not depend on the code and because no one had ever reported it to me.
I try to investigate the matter better.

**Comment by kethan1** [comment]
Sorry about the link, and yes, that's correct. Thanks for responding!

**Comment by stoddabr** [comment]
I'm having a similar issue. I created a quick workaround by creating a public method that resets the joystick. 
I have my code setup to call this from a script when the space bar is pressed so a user can manually reset it.

Here's a video of what it looks like in action: https://drive.google.com/file/d/1SCl_LKFH3rTzJhv2iqPkasFy6uB7vO82/view?usp=sharing

`	 /**
 	 * @desc Resets joystick position
 	 */
	 this.ResetJoy = function ()
 	{
		movedX=centerX;
		movedY=centerY;
		// Delete canvas
		context.clearRect(0, 0, canvas.width, canvas.height);
		// Redraw object
		drawExternal();
		drawInternal();
		//canvas.unbind('mousemove');
 	};`

**Comment by kethan1** [comment]
@bobboteck Maybe you take some inspiration from: https://github.com/yoannmoinet/nipplejs

**Comment by bobboteck** [comment]
Thanks to @amjad-ah for the fixing!
Sorry if in this period I can not keep up with the project, but I am very busy on other things.
