### ISSUE TITLE
Allow AddListener/Callback

### ISSUE THREAD

**Issue by kethan1** [bobboteck/JoyStick#20]
Currently, you have to use setTimout. Is there a way to do this with listeners/callbacks, and if there isn't could you add the ability? This would be **greatly** appreciated.

**Comment by bobboteck** [comment]
I'm looking for the possibility of use the Listeners

**Comment by bobboteck** [comment]
Hi @kethan1, I see your pull request #22, but testing your code I noticed some abnormal behavior.

![image](https://user-images.githubusercontent.com/5130571/132712340-6f437fa0-6bdf-48fc-98c1-1a0815cfda50.png)

As you can see, with your [code](https://github.com/kethan1/JoyStick/blob/7920e35250926f735a600770c98dcdbddde6928d/joy.js#L180) it can happen that by moving the cursor out of the canvas, it continues to update the position of the stick, when it is instead stopped. Contrary to how it currently works.

`callback((100*((movedX - centerX)/maxMoveStick)).toFixed(), (100*((movedY - centerY)/maxMoveStick)).toFixed());`

Looking at your change, it becomes clear to me that this is due to the calculations you introduced in the callback.
Thank you for the callback suggestion, but I believe I will not use your pull request, but will still implement a new version of the code that will make use of it.

**Comment by bobboteck** [comment]
Pushed first change of code in a new [brach](https://github.com/bobboteck/JoyStick/tree/callback).

Any suggestions are welcome!

**Comment by bobboteck** [comment]
Implemented the callback function
