### ISSUE TITLE
CSS breaks the script

### ISSUE THREAD

**Issue by Pioden** [bobboteck/JoyStick#4]
Your joystick code works perfectly until I try to position it on the screen using CSS. Let me give a code example.

Your HTML code reads
`<div id="joyDiv" style="width:200px;height:200px;margin-bottom:20px;"></div>`

and everything works just fine.

BUT, if you move the div to the left of the screen

`<div id="joyDiv" style="position:absolute; width:200px;height:200px;margin-bottom:20px;left:1000px;"></div>`

then the 'middle' of the joystick jerks to the right on mousedown event. On my screen I'm guessing the green centre moves around 50px to the right immediately on a click!

I *think* the problem lies with this function, but my JS isn't good enough to fix the bug :-(

    function onMouseMove(event)
    {
        if(pressed==1)
        {
            movedX=event.pageX;
            movedY=event.pageY;
            // Manage offset
            movedX-=canvas.offsetLeft;
            movedY-=canvas.offsetTop;
            // Delete canvas
            context.clearRect(0, 0, canvas.width, canvas.height);
            // Redraw object
            drawExternal();
            drawInternal();
        }

**Comment by bobboteck** [comment]
@Pioden sorry, but I realized that the change does not work properly, but that the code was valid even before.
The problem seems more related to the way you tried to place the JoyStick object on the page, ie use the "position: absolute" and the "left: 1000px".
Using a different approach to page placement, such as the one you report below, the JoyStick works correctly in all cases.

`<div id="joyDiv" style="width:200px;height:200px;margin-bottom:20px;float:right"></div>`

With this HTML you can use the old version of the JS file without problems.
Soon I will correct the last version on the repository, and open another Issue because I realized that it no longer works on Touch devices.
